# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"wezterm" = "ï„  wezterm"
"obsidian" = "ï‰ª obsidian"
"firefox" = "ï‰© firefox"
"character" = "ï‹ character map"
"mpv" = "ï€½ mpv"
"mail" = "ğŸ“§ email"
"volume" = "ï„° sound control"
"thunar" = "ï‹ files"

[other]
fallback_icon = "ï‹ unkown"
deduplicate_icons = true
separator = ": "
